=== LXM0521/Tux-Letter-Game/xsd/dico.xsd
<?xml version="1.0"?>
<xsd:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           elementFormDefault="qualified">

    
    <xsd:element name="dictionnaire" type="tux:Dictionnaire"/> 
    
    <!--DICTIONNAIRE
    -> CONTIENT DES NIVEAUX-->
    <xsd:complexType name="Dictionnaire">
        <xsd:sequence>
            <xsd:element name="mot" type="tux:Mot" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- WORD
    Un mot avec un numero de niveau
    -->
    <xsd:complexType name="Mot">
        <xsd:simpleContent>
            <xsd:extension base="tux:MotDef">
                <xsd:attribute name="numNiveau" type="tux:NumNiveau"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    
    <!--NUMNIVEAU
    -> TYPE SIMPLE NAME NUMNIVEAU AVEC RESTRICTION MIN INCLUSIVE 1 MAX INCLUSIVE 5
    -> cONTINET DES MOTS AVEC MINOCCURS 1 MAX OCCURS UNBOUNDED-->
    <xsd:simpleType name="NumNiveau">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="5"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!--WORDDEF
    -> TYPE STRINGMOTS AVEC RESTRIUCTIONS SUR LES CARACTERES SPECIAUX-->
    <xsd:simpleType name="MotDef">
        <xsd:restriction base="xsd:string">
             <xsd:pattern value="[a-zA-Z0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
       
</xsd:schema>

=== LXM0521/Tux-Letter-Game/xml/dico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<di:dictionnaire xmlns:di="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux file:///Users/lxm/NetBeansProjects/Tux/src/tux/xml/dico.xsd">
    
    <!-- MOT NIVEAU 1 -->
    <di:mot numNiveau="1">salut</di:mot>
    <di:mot numNiveau="1">alphabet</di:mot>
    <di:mot numNiveau="1">niveau</di:mot>
    
    <!-- MOT NIVEAU 2 -->
    <di:mot numNiveau="2">bienvenue</di:mot>
    <di:mot numNiveau="2">salutation</di:mot>
    <di:mot numNiveau="2">apprendre</di:mot>
    
    <!-- MOT NIVEAU 3 -->
    <di:mot numNiveau="3">transformation</di:mot>
    <di:mot numNiveau="3">affectation</di:mot>
    <di:mot numNiveau="3">apprentissage</di:mot>
    
    <!-- MOT NIVEAU 4 -->
    <di:mot numNiveau="4">externalisation</di:mot>
    <di:mot numNiveau="4">gouvernement</di:mot>
    
    <!-- MOT NIVEAU 5 -->
    <di:mot numNiveau="5">anticonstitutionnellement</di:mot>
    <di:mot numNiveau="5">intergouvernementalisation</di:mot>
    <di:mot numNiveau="5">d√©constitutionnalisassions</di:mot>
    


</di:dictionnaire>
